### ISSUE TITLE
Lights don't work

### ISSUE THREAD

**Issue by Termin8or** [Ritsu95/3D-Game-Engine-ThinMatrix#1]
Somewhere after tutorial 23, your lights stopped, I presume you did something wrong.

**Comment by ProgrammingInitialized** [comment]
what do you mean

like gone black?

or your display stops working

**Comment by BasicsCoding** [comment]
the lights do not emit light what so ever.

**Comment by Ritsu95** [comment]
@Termin8or They work on my local project :/
![captura](https://cloud.githubusercontent.com/assets/6287958/14789253/fcbc3892-0b0b-11e6-9bf3-4fb97037b542.PNG)

**Comment by Termin8or** [comment]
Hmmm OK, it was probs an error on my end.
