### ISSUE TITLE
Flowers are rendering in mid-air

### ISSUE THREAD

**Issue by BasicsCoding** [Ritsu95/3D-Game-Engine-ThinMatrix#2]
The flowers are rendering in mid-air, when there a dip in the ground they will render in their normal position
![glitch](https://cloud.githubusercontent.com/assets/13019863/13685401/2cc41e4c-e708-11e5-8d7d-a94e004a17b1.png)

**Comment by Ritsu95** [comment]
That's because all of the flowers are from a unique model and not a single model per flower

**Comment by Termin8or** [comment]
@Ritsu95 @BasicsCoding I believe it's actually to do with the way they spawn, having a unique model wouldn't change the way it's y value is decided. I may be wrong.

**Comment by Termin8or** [comment]
@Ritsu95 Are you planning on updating this as thin started his tutorials again, he's done quite a bit more.

**Comment by Ritsu95** [comment]
@Termin8or They Y value is calculated by `terrain.getHeightOfTerrain(x,` z);` btw, I've been busy with work and studies, but i'm gonna try to continue and update the repository to the episode 43 + OpenGL Water rendering.
@BasicsCoding  If you check grassModel.obj you'll see that they are a bunch of objects on a same model, so if you want to correct that error you need to change grassModel.obj to a single object and render it multiple times on a zone so each of them gets its own terrain height
